// SPDX-License-Identifier: Apache-2.0
// This code has been partially generated by an AI.

package plugin

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestSplitPackagersDefaults(t *testing.T) {
	t.Parallel()

	require.Equal(t, []string{"deb", "rpm", "apk"}, SplitPackagers(""))
}

func TestSplitPackagersParsesCSV(t *testing.T) {
	t.Parallel()

	require.Equal(t, []string{"deb", "rpm"}, SplitPackagers("deb, rpm"))
}

func TestBuildCommands(t *testing.T) {
	t.Parallel()

	commands := BuildCommands("nfpm.yaml", "dist", []string{"deb", "rpm"})
	require.Len(t, commands, 2)
	require.Equal(t, []string{"nfpm", "package", "--config", "nfpm.yaml", "--target", "dist", "--packager", "deb"}, commands[0])
	require.Equal(t, []string{"nfpm", "package", "--config", "nfpm.yaml", "--target", "dist", "--packager", "rpm"}, commands[1])
}

func TestRunCommandsDryRun(t *testing.T) {
	t.Parallel()

	var out bytes.Buffer
	var errBuf bytes.Buffer
	err := RunCommands([][]string{{"nfpm", "package", "--config", "nfpm.yaml"}}, &out, &errBuf, true)
	require.NoError(t, err)
	require.Contains(t, out.String(), "[dry-run] would run")
}
