# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The packager-nfpm Authors

version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused