// SPDX-License-Identifier: Apache-2.0
// This code has been partially generated by an AI.

package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/SemRels/packager-nfpm/internal/plugin"
)

const pluginSchemaVersion = 1

func main() {
	os.Exit(run(os.Stdout, os.Stderr, os.Getenv))
}

func run(stdout, stderr io.Writer, getenv func(string) string) int {
	_, _ = fmt.Fprintf(stderr, "plugin_schema_version=%d\n", pluginSchemaVersion)

	version := getenv("SEMREL_VERSION")
	if version == "" {
		version = getenv("SEMREL_NEXT_VERSION")
	}
	if version == "" {
		fmt.Fprintln(stderr, "packager-nfpm: SEMREL_VERSION is required")
		return 1
	}

	configPath := getenv("SEMREL_PLUGIN_CONFIG")
	if configPath == "" {
		configPath = "nfpm.yaml"
	}

	targetDir := getenv("SEMREL_PLUGIN_TARGET")
	if targetDir == "" {
		targetDir = "dist"
	}

	packagers := plugin.SplitPackagers(getenv("SEMREL_PLUGIN_PACKAGERS"))
	commands := plugin.BuildCommands(configPath, targetDir, packagers)
	dryRun := strings.EqualFold(getenv("SEMREL_DRY_RUN"), "true")

	if err := plugin.RunCommands(commands, stdout, stderr, dryRun); err != nil {
		fmt.Fprintln(stderr, "packager-nfpm:", err)
		return 1
	}

	if dryRun {
		fmt.Fprintf(stdout, "packager-nfpm: [dry-run] package pipeline resolved for version %s\n", version)
		return 0
	}

	fmt.Fprintf(stdout, "packager-nfpm: built packages for version %s\n", version)
	return 0
}
